# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20171029_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('can create_update_delete', 'create_update_delete author'),)},
        ),
    ]
