# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20171101_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('can create_update_delete author', 'create update delete author'),)},
        ),
    ]
